# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\"\x16\n\x05\x43laim\x12\r\n\x05title\x18\x01 \x01(\t\"\x12\n\x10GetClaimsRequest\"+\n\x11GetClaimsResponse\x12\x16\n\x06\x63laims\x18\x01 \x03(\x0b\x32\x06.Claim2<\n\x04\x41uth\x12\x34\n\tGetClaims\x12\x11.GetClaimsRequest\x1a\x12.GetClaimsResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CLAIM']._serialized_start=14
  _globals['_CLAIM']._serialized_end=36
  _globals['_GETCLAIMSREQUEST']._serialized_start=38
  _globals['_GETCLAIMSREQUEST']._serialized_end=56
  _globals['_GETCLAIMSRESPONSE']._serialized_start=58
  _globals['_GETCLAIMSRESPONSE']._serialized_end=101
  _globals['_AUTH']._serialized_start=103
  _globals['_AUTH']._serialized_end=163
# @@protoc_insertion_point(module_scope)
