# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetServiceClaims.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16GetServiceClaims.proto\x12\x10\x41uthorizeService\"\x0e\n\x0c\x45mptyRequest\"\"\n\x11GetClaimListReply\x12\r\n\x05items\x18\x01 \x03(\t2a\n\tGetClaims\x12T\n\rGetClaimsList\x12\x1e.AuthorizeService.EmptyRequest\x1a#.AuthorizeService.GetClaimListReplyB\x0b\xaa\x02\x08\x41uth.Apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetServiceClaims_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\010Auth.Api'
  _globals['_EMPTYREQUEST']._serialized_start=44
  _globals['_EMPTYREQUEST']._serialized_end=58
  _globals['_GETCLAIMLISTREPLY']._serialized_start=60
  _globals['_GETCLAIMLISTREPLY']._serialized_end=94
  _globals['_GETCLAIMS']._serialized_start=96
  _globals['_GETCLAIMS']._serialized_end=193
# @@protoc_insertion_point(module_scope)
