# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AuthGrpcService.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x41uthGrpcService.proto\x12\x0b\x41uthService\"$\n\x10\x41uthTokenRequest\x12\x10\n\x08JwtToken\x18\x01 \x01(\t\"E\n\x0cGetUserReply\x12\x11\n\tFirstName\x18\x01 \x01(\t\x12\x10\n\x08LastName\x18\x02 \x01(\t\x12\x10\n\x08UserName\x18\x03 \x01(\t\"!\n\x0fValidTokenReply\x12\x0e\n\x06IsOkay\x18\x01 \x01(\x08\")\n\nClaimModel\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\":\n\x0f\x43laimArrayReply\x12\'\n\x06\x43laims\x18\x01 \x03(\x0b\x32\x17.AuthService.ClaimModel\"3\n\x12IsAuthorizeRequest\x12\x0e\n\x06UserId\x18\x01 \x01(\t\x12\r\n\x05\x43laim\x18\x02 \x01(\t\"&\n\x10IsAuthorizeReply\x12\x12\n\nAuthorized\x18\x01 \x01(\x08\",\n\x16IsAuthorizedTokenReply\x12\x12\n\nAuthorized\x18\x01 \x01(\x08\"8\n\x18IsAuthorizedTokenRequest\x12\r\n\x05Token\x18\x01 \x01(\t\x12\r\n\x05\x43laim\x18\x02 \x01(\t2\x97\x03\n\x0b\x41uthService\x12\x43\n\x07GetUser\x12\x1d.AuthService.AuthTokenRequest\x1a\x19.AuthService.GetUserReply\x12I\n\nValidToken\x12\x1d.AuthService.AuthTokenRequest\x1a\x1c.AuthService.ValidTokenReply\x12H\n\tGetClaims\x12\x1d.AuthService.AuthTokenRequest\x1a\x1c.AuthService.ClaimArrayReply\x12M\n\x0bIsAuthorize\x12\x1f.AuthService.IsAuthorizeRequest\x1a\x1d.AuthService.IsAuthorizeReply\x12_\n\x11IsAuthorizedToken\x12%.AuthService.IsAuthorizedTokenRequest\x1a#.AuthService.IsAuthorizedTokenReplyB\x0b\xaa\x02\x08\x41uth.Apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AuthGrpcService_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\010Auth.Api'
  _globals['_AUTHTOKENREQUEST']._serialized_start=38
  _globals['_AUTHTOKENREQUEST']._serialized_end=74
  _globals['_GETUSERREPLY']._serialized_start=76
  _globals['_GETUSERREPLY']._serialized_end=145
  _globals['_VALIDTOKENREPLY']._serialized_start=147
  _globals['_VALIDTOKENREPLY']._serialized_end=180
  _globals['_CLAIMMODEL']._serialized_start=182
  _globals['_CLAIMMODEL']._serialized_end=223
  _globals['_CLAIMARRAYREPLY']._serialized_start=225
  _globals['_CLAIMARRAYREPLY']._serialized_end=283
  _globals['_ISAUTHORIZEREQUEST']._serialized_start=285
  _globals['_ISAUTHORIZEREQUEST']._serialized_end=336
  _globals['_ISAUTHORIZEREPLY']._serialized_start=338
  _globals['_ISAUTHORIZEREPLY']._serialized_end=376
  _globals['_ISAUTHORIZEDTOKENREPLY']._serialized_start=378
  _globals['_ISAUTHORIZEDTOKENREPLY']._serialized_end=422
  _globals['_ISAUTHORIZEDTOKENREQUEST']._serialized_start=424
  _globals['_ISAUTHORIZEDTOKENREQUEST']._serialized_end=480
  _globals['_AUTHSERVICE']._serialized_start=483
  _globals['_AUTHSERVICE']._serialized_end=890
# @@protoc_insertion_point(module_scope)
