# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: claims.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63laims.proto\x12\x06\x63laims\"\x16\n\x05\x43laim\x12\r\n\x05title\x18\x01 \x01(\t\"\x12\n\x10GetClaimsRequest\"2\n\x11GetClaimsResponse\x12\x1d\n\x06\x63laims\x18\x01 \x03(\x0b\x32\r.claims.Claim2L\n\x06\x43laims\x12\x42\n\tGetClaims\x12\x18.claims.GetClaimsRequest\x1a\x19.claims.GetClaimsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'claims_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CLAIM']._serialized_start=24
  _globals['_CLAIM']._serialized_end=46
  _globals['_GETCLAIMSREQUEST']._serialized_start=48
  _globals['_GETCLAIMSREQUEST']._serialized_end=66
  _globals['_GETCLAIMSRESPONSE']._serialized_start=68
  _globals['_GETCLAIMSRESPONSE']._serialized_end=118
  _globals['_CLAIMS']._serialized_start=120
  _globals['_CLAIMS']._serialized_end=196
# @@protoc_insertion_point(module_scope)
