# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import GetServiceClaims_pb2 as GetServiceClaims__pb2


class GetClaimsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetClaimsList = channel.unary_unary(
                '/AuthorizeService.GetClaims/GetClaimsList',
                request_serializer=GetServiceClaims__pb2.EmptyRequest.SerializeToString,
                response_deserializer=GetServiceClaims__pb2.GetClaimListReply.FromString,
                )


class GetClaimsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetClaimsList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GetClaimsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetClaimsList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClaimsList,
                    request_deserializer=GetServiceClaims__pb2.EmptyRequest.FromString,
                    response_serializer=GetServiceClaims__pb2.GetClaimListReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AuthorizeService.GetClaims', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GetClaims(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetClaimsList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AuthorizeService.GetClaims/GetClaimsList',
            GetServiceClaims__pb2.EmptyRequest.SerializeToString,
            GetServiceClaims__pb2.GetClaimListReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
