# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Camera_pb2 as Camera__pb2


class CameraStub(object):
    """Define the service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamImages = channel.unary_stream(
                '/CameraService.Camera/StreamImages',
                request_serializer=Camera__pb2.ImageStreamRequest.SerializeToString,
                response_deserializer=Camera__pb2.ImageResponse.FromString,
                )


class CameraServicer(object):
    """Define the service
    """

    def StreamImages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CameraServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamImages': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamImages,
                    request_deserializer=Camera__pb2.ImageStreamRequest.FromString,
                    response_serializer=Camera__pb2.ImageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CameraService.Camera', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Camera(object):
    """Define the service
    """

    @staticmethod
    def StreamImages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/CameraService.Camera/StreamImages',
            Camera__pb2.ImageStreamRequest.SerializeToString,
            Camera__pb2.ImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
