# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Camera.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x43\x61mera.proto\x12\rCameraService\"k\n\x12ImageStreamRequest\x12\x19\n\x11\x63onnection_string\x18\x01 \x01(\t\x12\x10\n\x08UserName\x18\x02 \x01(\t\x12\x10\n\x08Password\x18\x03 \x01(\t\x12\x16\n\x0e\x46ramePerSecond\x18\x04 \x01(\x05\"\"\n\rImageResponse\x12\x11\n\tImageData\x18\x01 \x01(\x0c\x32[\n\x06\x43\x61mera\x12Q\n\x0cStreamImages\x12!.CameraService.ImageStreamRequest\x1a\x1c.CameraService.ImageResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Camera_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IMAGESTREAMREQUEST']._serialized_start=31
  _globals['_IMAGESTREAMREQUEST']._serialized_end=138
  _globals['_IMAGERESPONSE']._serialized_start=140
  _globals['_IMAGERESPONSE']._serialized_end=174
  _globals['_CAMERA']._serialized_start=176
  _globals['_CAMERA']._serialized_end=267
# @@protoc_insertion_point(module_scope)
