# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlateDetection.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14PlateDetection.proto\"\x1c\n\x0b\x43\x61meraFrame\x12\r\n\x05\x66rame\x18\x01 \x01(\x0c\x32>\n\x0ePlateDetection\x12,\n\x0cStreamCamera\x12\x0c.CameraFrame\x1a\x0c.CameraFrame0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PlateDetection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CAMERAFRAME']._serialized_start=24
  _globals['_CAMERAFRAME']._serialized_end=52
  _globals['_PLATEDETECTION']._serialized_start=54
  _globals['_PLATEDETECTION']._serialized_end=116
# @@protoc_insertion_point(module_scope)
