# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ReadPlate_pb2 as ReadPlate__pb2


class ReadPlateStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadPlates = channel.unary_stream(
                '/PlateDetection.ReadPlate/ReadPlates',
                request_serializer=ReadPlate__pb2.ReadPlateRequest.SerializeToString,
                response_deserializer=ReadPlate__pb2.ReadPlateReply.FromString,
                )


class ReadPlateServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReadPlates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReadPlateServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadPlates': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadPlates,
                    request_deserializer=ReadPlate__pb2.ReadPlateRequest.FromString,
                    response_serializer=ReadPlate__pb2.ReadPlateReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PlateDetection.ReadPlate', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ReadPlate(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReadPlates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/PlateDetection.ReadPlate/ReadPlates',
            ReadPlate__pb2.ReadPlateRequest.SerializeToString,
            ReadPlate__pb2.ReadPlateReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
