# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReadPlate.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fReadPlate.proto\x12\x0ePlateDetection\" \n\x10ReadPlateRequest\x12\x0c\n\x04guid\x18\x01 \x01(\t\"3\n\x0eReadPlateReply\x12\r\n\x05plate\x18\x01 \x01(\t\x12\x12\n\nimage_path\x18\x02 \x01(\t2]\n\tReadPlate\x12P\n\nReadPlates\x12 .PlateDetection.ReadPlateRequest\x1a\x1e.PlateDetection.ReadPlateReply0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ReadPlate_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_READPLATEREQUEST']._serialized_start=35
  _globals['_READPLATEREQUEST']._serialized_end=67
  _globals['_READPLATEREPLY']._serialized_start=69
  _globals['_READPLATEREPLY']._serialized_end=120
  _globals['_READPLATE']._serialized_start=122
  _globals['_READPLATE']._serialized_end=215
# @@protoc_insertion_point(module_scope)
