# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReadPlate.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fReadPlate.proto\x12\x0ePlateDetection\" \n\x10ReadPlateRequest\x12\x0c\n\x04guid\x18\x01 \x01(\t\" \n\x0eReadPlateReply\x12\x0e\n\x06result\x18\x01 \x01(\t2[\n\tReadPlate\x12N\n\nReadPlates\x12 .PlateDetection.ReadPlateRequest\x1a\x1e.PlateDetection.ReadPlateReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ReadPlate_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_READPLATEREQUEST']._serialized_start=35
  _globals['_READPLATEREQUEST']._serialized_end=67
  _globals['_READPLATEREPLY']._serialized_start=69
  _globals['_READPLATEREPLY']._serialized_end=101
  _globals['_READPLATE']._serialized_start=103
  _globals['_READPLATE']._serialized_end=194
# @@protoc_insertion_point(module_scope)
